# Site wide configuration

title:            Gabriel Araujo
locale:           pt_BR
url:              http://gabrielaraujo.me


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Gabriel Araujo
  avatar: bio-photo.jpg
  bio: "An ever curious computer scientist, programmer, professor, lover and tech enthusiast."
  email:
  disqus-shortname: gabrielaraujof
  twitter: gabrielfeear
  facebook: GabrielAraujoF
  google:
    plus: GabrielAraujoF
    analytics: UA-50425694-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: gabrielaraujof
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: gabrielaraujof
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
